# Netlify Configuration File

[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'"

[dev]
  command = "npm run start"
  port = 3000

# Serverless function for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
